calibration:
  angle_set_freq: 30
  do_spectrum: 1
  downsample: 1
  filter_data: bandpass
  gain_mark: 50
  l_flatness: 10
  optical_sens_tolerance: 100.0
  optical_sensitivity: 1350.0
  phase_mark: 50
  plot: true
  r_flatness: 100
  reference_sensitivity: 105.532
  slope_check: 5
current: true
function_generator:
  generator_id: TCPIP0::10.88.5.166::inst0::INSTR
  generator_max_vpp: 40
  generator_sweep_start_freq: 5
  generator_sweep_stop_freq: 200
  generator_sweep_time: 20
  generator_sweep_type: SINusoid
opt_measurement:
  channels: 2
  project: 2CH.ssd
  sampling_rate: 800
  sensor_type: Accelerometer
ref_device:
  channel: ai2
  name: cDAQ1Mod1
ref_measurement:
  measure_time: 25
  number_of_samples_per_channel: 294400
  sample_rate: 12800
save_data:
  S_N: measured_data.csv
  auto_export: true
  calibration_export: C:\Users\PC/Documents\Sylex_sensors_export\calibration
  db_folder: C:/Users/PC/Desktop/Sylex/testDB
  export_local_server: true
  main_folder: C:\Users\PC/Documents\Sylex_sensors_export
  modbus_folder: C:/Users/PC/Desktop/Sylex/Sentinel/Sentinel2_Dynamic_Modbus_v1_0_7
  opt_export: C:\Users\PC/Documents\Sylex_sensors_export\optical
  opt_export_raw: C:\Users\PC/Documents\Sylex_sensors_export\optical_raw
  ref_export: C:\Users\PC/Documents\Sylex_sensors_export\reference
  ref_export_raw: C:\Users\PC/Documents\Sylex_sensors_export\reference_raw
  stats_folder: C:/Users/PC/Desktop/Sylex/testDB
