current: true
calibration:
  do_spectrum: 1
  downsample: 1
  filter_data: high-pass
  gain_mark: '150'
  optical_sensitivity: '0'
  plot: 0
opt_measurement:
  project: test.ssd
  sampling_rate: '800'
  sensor_type: accelerometer
ref_device:
  channel: ai0
  name: ''
ref_measurement:
  measure_time: '25'
  number_of_samples_per_channel: 320000
  sample_rate: '12800'
save_data:
  S_N: measured_data.csv
  calibration_export: ''
  main_folder: C:/Users/lukac/Documents/Sylex_sensors_export
  opt_export: C:/Users/lukac/Documents/Sylex_sensors_export/optical
  opt_export_raw: C:/Users/lukac/Documents/Sylex_sensors_export/optical_raw
  ref_export: C:/Users/lukac/Documents/Sylex_sensors_export/reference
  ref_export_raw: C:/Users/lukac/Documents/Sylex_sensors_export/reference_raw
  sentinel_D_folder: C:/Users/lukac/Desktop/Sylex/Sentinel/Sentinel2_Dynamic_v0_4_1/Sentinel2_Dynamic_v0_4_1
  sentinel_S_folder:
