device:
  channel: ai2
  name: cDAQ1Mod1
ref_measurement:
  number_of_samples_per_channel: 320000
  sample_rate: 12800
save_data:
  destination_folder: C:/Users/lukac/Desktop/Sylex/TEST_DATA/REF
  ref_name: ref_data.txt
