device:
  channel: ai2
  name: cDAQ1Mod1
measurement:
  number_of_samples_per_channel: 320000
  sample_rate: 12800
save_data:
  destination_folder: C:/Users/lukac/Desktop/Sylex/AutoKali/App/appka
  ref_name: samples.txt
