device:
  name: cDAQ1Mod1
  channel: ai2

measurement:
  sample_rate: 12800
  number_of_samples_per_channel: 80000

save_data:
  ref_name: 'testData.txt'
  destination_folder: 'C:/Users/lukac/Desktop/Sylex/TEST_DATA/REF'